#!/bin/bash

DIR="/opt/magicmouse-hid"
cd ${DIR}

# Install drive through DKMS
chmod u+x ${DIR}/scripts/install.sh
${DIR}/scripts/install.sh

# Copy script to load the driver to OPT directory
chmod +x ${DIR}/magic-mouse-2-add.sh

# Copy udev rule and reload udev
udevadm control -R

# Disable eSCO mode in Bluetooth to fix disconnection problems with the mouse
echo 1 | tee /sys/module/bluetooth/parameters/disable_esco
systemctl restart bluetooth
# persist eSCO mode in Bluetooth setting
echo "options bluetooth disable_esco=1" | tee /etc/modprobe.d/bluetooth-tweaks.conf