#!/bin/bash

DIR="/opt/magicmouse-hid"
cd ${DIR}

# Remove drive through DKMS
chmod u+x ${DIR}/scripts/remove.sh
${DIR}/scripts/remove.sh

# Reload udev after removing the udev rule
udevadm control -R

# Restart Bluetooth
systemctl restart bluetooth
